services:
  backend:
    build: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: vite_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - app-network
    env_file:
      - ./frontend/.env


networks:
  app-network:
    driver: bridge
